apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-client
  template:
    metadata:
      labels:
        app: ping-client
    spec:
      containers:
        - name: ping-client
          image: wcygan/monorepo-jib-proto-client