apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: client-server-application
requires:
  - configs:
      - server
    path: server/skaffold.yaml
  - configs:
      - client
    path: client/skaffold.yaml
  - configs:
      - monitoring-installation
    path: monitoring/skaffold.yaml