apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-server
  template:
    metadata:
      labels:
        app: ping-server
    spec:
      containers:
      - name: ping-server
        image: wcygan/monorepo-jib-proto-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ping-server-service
spec:
  selector:
    app: ping-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080